title: Mdkkt | もんだいかいけつ

permalink: /Solution/:title/

plugins: [jekyll-paginate]

baseurl: /mdkkt

markdown: kramdown
highlighter: rouge
paginate: 20

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
